### ISSUE TITLE
추천 결과 프래그먼트 다시 들어갈시 에러발생

### ISSUE THREAD

**Issue by LimSeungW** [ys05059/24mo#21]
추천 결과 프래그먼트에서 추천리스트가 다 뜬후, 상단에 홈으로 이동버튼눌러서 
다시 추천 태그를 통해 추천결과 프래그먼트 진입시 앱이 종료되어버림.

**Comment by ys05059** [comment]
도수가 낮은 태그 오류 있던거 잡았습니다! 그리고 지금 #가장 많이 팔리는 태그는 동작이 아직 안됩니다

**Comment by ys05059** [comment]
#가장 많이 팔리는 태그 구현 완료했습니다
