### ISSUE TITLE
바코드검색 2~3번반복실행시 앱종료

### ISSUE THREAD

**Issue by LimSeungW** [ys05059/24mo#33]
로그만 보면 바코드 프래그먼트 내의 OnResume().에서 Null값 관련 예외발생으로 인한 에러인것같습니다

**Comment by ys05059** [comment]
바코드 다이얼로그 프래그먼트 외부를 눌렀을 때 프래그먼트가 닫힘으로 다음 프래그먼트를 띄울 수 없어 발생하는 이슈로 확인됨
null cannot be cast to non-null type Main.MainActivity
null일 때 따로 처리해줌으로써 해결
