### ISSUE TITLE
체크박스 이벤트 리스너 이슈

### ISSUE THREAD

**Issue by LimSeungW** [ys05059/24mo#9]
체크박스 선택시 장바구니에 값을 어떻게 전달할것인가.
List에서 CartItem에 항목마다 체크가 되었는가 안되었는가 상태를 표시하는 boolean변수하나 필요할것같습니다

**Comment by ys05059** [comment]
제가 확인해볼게요

**Comment by ys05059** [comment]
wineDTO에 checked 변수 만들어서 해결했습니다
